# TODO Define the suffix and prefix properties for the InternalResourceViewResolver Spring:
  spring:
    mvc:
      view:
        prefix: /WEB-INF/views/
        suffix: .jsp

    jpa:
      hibernate:
        ddl-auto: none

    datasource:
      schema: classpath:/rewards/testdb/schema.sql
      data: classpath:/rewards/testdb/data.sql

  logging:
    level:
      org.springframework: INFO